version: "3"
services:
    php:
        container_name: phalcon-php
        build:
            context: ./php
            dockerfile: dockerfile
            args:
                - WITH_XDEBUG=true
        working_dir: /var/www/html
        volumes:
            - ./php/asset/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
            - ./phalcon-sample:/var/www/html
        command: bash -c "php-fpm"
        restart: always
    web:
        container_name: phalcon-nginx
        image: nginx:1.17.8
        command: ["nginx", "-g", "daemon off;"]
        depends_on:
            - php
        volumes:
            - ./nginx/asset/default.conf:/etc/nginx/conf.d/default.conf
            - ./phalcon-sample:/var/www/html
        ports:
            - "3000:10"
            - "3001:100"
        links:
            - php
        restart: always
